### ISSUE TITLE
Get working on windows

### ISSUE THREAD

**Issue by peterabbott** [peterabbott/kitchen-docker#1]
try and get working on windows

**Comment by markl17** [comment]
hi mr. abbott  i have following .kitchen .yml file
'''javascript
---
driver:
  name: docker
  socket: "tcp://192.168.59.103:2376"
  binary: docker.exe
  use_sudo: false
driver_config:
  require_chef_omnibus: 10.18.2
  
  run_command: /usr/sbin/sshd -D -o UseDns=no UsePam=no
  use_sudo: false
  provisioner_command:
    - chown kitchen.kitchen /tmp/kitchen
provisioner:
  name: chef_zero
  client_rb:
    no_proxy: 127.0.0.1
platforms:
  - name: dev
    driver_config:
      image: "repo:ubuntu"
      platform: "ubuntu"
suites:
  - name: webserver
    date_bags_path: databags
    roles_path: kitchen_roles
    run_list:
      - recipe[apache]
  - name: db01
    data_bags_path: databags
    roles_path: kitchen_roles
i get an error 
C:\Users\markl_000>kitchen create
-----> Starting Kitchen (v1.3.1)
←[36m-----> Creating <webserver-dev>...←[0m
←[0mm       Sending build context to Docker daemon  2.56 kB
←[36m       Sending build context to Docker daemon ←[0m
←[36m       Step 0 : FROM repo:ubuntu←[0m
←[36m       Pulling repository repo←[0m
←[36m       time="2015-02-23T11:29:24-05:00" level="info" msg="Error: image
ary/repo:ubuntu not found" ←[0m
←[31m>>>>>> ------Exception-------←[0m
←[31m>>>>>> Class: Kitchen::ActionFailed←[0m
←[31m>>>>>> Message: Failed to complete #create action: [Expected process t
t with [0], but received '1'
---- Begin output of docker.exe -H tcp://192.168.59.103:2376 build - ----
STDOUT: Step 0 : FROM repo:ubuntu
Pulling repository repo
STDERR: Sending build context to Docker daemon  2.56 kB
Sending build context to Docker daemon
time="2015-02-23T11:29:24-05:00" level="info" msg="Error: image library/rep
ntu not found"
---- End output of docker.exe -H tcp://192.168.59.103:2376 build - ----
Ran docker.exe -H tcp://192.168.59.103:2376 build - returned 1]←[0m
←[31m>>>>>> ----------------------←[0m
←[31m>>>>>> Please see .kitchen/logs/kitchen.log for more details←[0m
←[31m>>>>>> Also try running `kitchen diagnose --all` for configuration
←[0m
please help

**Comment by peterabbott** [comment]
are you trying to use a private docker image? Looking at the output, image: "repo:ubuntu" does not look right. 

Unless you want to use a specific image, test kitchen is often good a deciphering from the name attribute.

for example:

```
platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.4
```

If you really need to specify image, you can always verify what is available by trying `docker -H <host> run <image> bash` and then taking <image> and adding that to your test kitchen setup.

**Comment by peterabbott** [comment]
@markl17 did you get any further with this?

**Comment by markl17** [comment]
yes i did thank you so much

**Comment by huntertj** [comment]
any additional info on this? I'm using boot2Docker and compiled docker.exe 
kitchen fails with ">>>>>> Message: Could not parse Docker inspect output for container SSH port" 
it appears the driver is expecting some values here
PortBindings"=>{"22/tcp"=>[{"HostIp"=>"", "HostPort"=>""}]},

**Comment by peterabbott** [comment]
Can you verify that the container is running with `docker ps`?

**Comment by huntertj** [comment]
it appears the container is not running from the converge
04:04:10 {local} /c/dev/aw-mygea$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
04:04:44 {local} /c/dev/aw-mygea$ docker ps  -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                      PORTS               NAMES
05af5cb5de71        c954b1e02a87        "\"/usr/sbin/sshd -D   41 seconds ago      Exited (1) 35 seconds ago                       focused_bohr

**Comment by peterabbott** [comment]
What is your .kitchen.yml file? Have you changed the exec command?

I am not on windows to can't verify myself. I had just been helping
@markl17 getting it working.

**Comment by huntertj** [comment]
``` ruby
driver:
  name: docker
driver_config:
  use_sudo: false
  provisioner_command:
    - chown kitchen.kitchen /tmp/kitchen
```

I suspect the docker.exe and boot2docker (v1.5.0) isn't working with the kitchen-docker cmd (/usr/sbin/ssh) or my environment isn't setup the way @markl17 is

**Comment by tknerr** [comment]
I'm joining you guys. Lets make it work on Windows! :-)

@huntertj stuck at the same place as you currently:

```
C:\Repos\_github\bills-kitchen\target\build\repo\fundamentals-with-tests\chef-repo\cookbooks\motd>kitchen converge
-----> Starting Kitchen (v1.4.0.beta.2)
       Containers: 4
       Images: 16
       Storage Driver: aufs
        Root Dir: /mnt/sda1/var/lib/docker/aufs
        Backing Filesystem: extfs
        Dirs: 24
       Execution Driver: native-0.2
       Kernel Version: 3.18.5-tinycore64
       Operating System: Boot2Docker 1.5.0 (TCL 5.4); master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
       CPUs: 8
       Total Memory: 1.961 GiB
       Name: boot2docker
       ID: L2UA:J7IL:A42E:3HRB:SBOF:SRMI:75WG:4T47:TEN7:QCDU:YXQN:ZEGV
       Debug mode (server): true
       Debug mode (client): false
       File Descriptors: 12
       Goroutines: 15
       EventsListeners: 0
       Init Path: /usr/local/bin/docker
       Docker Root Dir: /mnt/sda1/var/lib/docker
-----> Creating <default-centos-65>...
>>>>>> Create failed on instance <default-centos-65>.
>>>>>> Please see .kitchen/logs/default-centos-65.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Could not parse Docker inspect output for container SSH port
>>>>>> ----------------------
```

**Comment by peterabbott** [comment]
You can grab the windows fork from my repo if you want to test. Was having
some merge issues after the flurry of activity the other day abd didn't
have the time to quickly fix. Should be able to look at it in about an
hour.

**Comment by peterabbott** [comment]
Ha. I just realised this comment was on my branch. So I'll look at it more
detail to see what I missed. Maybe I'll grab a Windows VM from MS site to
replicate myself.

**Comment by peterabbott** [comment]
Everything is merged from the portech driver. If you have a look at the branch, I'll have to try on a Windows VM tomorrow (in NZ)

**Comment by huntertj** [comment]
@peterabbott I just tested with your latest merges and I have success. As a side node I moved to the 1.6.0 versions of boot2docker.iso and docker.exe from https://groups.google.com/forum/#!forum/docker-dev I don't think its related but may be. @tknerr if you are still having issues I would be glad to help debug

**Comment by tknerr** [comment]
hey @peterabbott @huntertj, thanks for the quick responses!

So I got it working with the original "kitchen-docker" driver. The only thing I needed to change was the `> NUL` bit.

Sorry, somehow I landed here, but I actually don't really know why I would need "kitchen-docker_ssh" instead of plain "kitchen-docker". What's the difference in this fork?

**Comment by tknerr** [comment]
@huntertj thanks for pointing out the 1.6.rc builds of docker.exe on the mailing list. I was taking the master branch .exe builds with 1.5 iso and fiddling with the protocol version mismatch earlier... ;-)

**Comment by huntertj** [comment]
@tknerr I did the same thing with docker.exe and ended up compiling my own with the API to match before I found the 1.6.0 builds, I figured it may help more people getting started until boot2docker 1.6.0 is officially released

**Comment by peterabbott** [comment]
@tknerr the only real difference between kitchen-docker and kitchen-docker_ssh is that I was getting tired of waiting for portertech to respond to PR's, so I started pushing a new branched version to the rubygems repo (instead of having to add github repos to Gemfile).

Others have done the same, @marcy-terui has done the same with https://github.com/marcy-terui/kitchen-docker_cli/ but this uses the exec command instead of launching a ssh agent to handle the provisioning. 

Personally I am in favour of ssh options as it fits with how most the other drivers work.

**Comment by peterabbott** [comment]
I have just tested on the mac with docker 1.6.0 now that it is officially release and everything ran fine. 

CircleCI integration tests ran as well, but they run their own patched version of Docker so might not be 1.6 yet.

Going to try the PR again.

**Comment by marcy-terui** [comment]
@peterabbott 

Speak for yourself.

My plugin (https://github.com/marcy-terui/kitchen-docker_cli/) is not same your plugin.
I made it from scratch. It's not a branch.

You seem to have a negative feeling to portertech, but I haven't.

I felt that does not match the speed and direction of development.
So, I just chose a different road.That's all.

**Comment by peterabbott** [comment]
Sorry for the confusion.

Not negative feeling, just frustration at the speed of responding to
questions and PR's, especially considering the pace that Docker itself
changes.
